# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 08:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=256, unique=True)),
                ('short_url', models.CharField(db_index=True, max_length=22, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text=b'JSON format', verbose_name='metadata contents')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
        ),
    ]
