# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ober', '0002_auto_20170724_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='doi',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
