# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ober', '0004_auto_20170724_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='url',
            field=models.URLField(default='', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
