# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ober', '0005_publisher_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='rss_url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
